//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Conexion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ComunidadesGPMEntities : DbContext
    {
        public ComunidadesGPMEntities()
            : base("name=ComunidadesGPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int Sp_AsignarModuloPrivilegioCambiarEstado(Nullable<int> idAsinarModuloPrivilegio, Nullable<bool> nuevoEstado)
        {
            var idAsinarModuloPrivilegioParameter = idAsinarModuloPrivilegio.HasValue ?
                new ObjectParameter("IdAsinarModuloPrivilegio", idAsinarModuloPrivilegio) :
                new ObjectParameter("IdAsinarModuloPrivilegio", typeof(int));
    
            var nuevoEstadoParameter = nuevoEstado.HasValue ?
                new ObjectParameter("NuevoEstado", nuevoEstado) :
                new ObjectParameter("NuevoEstado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_AsignarModuloPrivilegioCambiarEstado", idAsinarModuloPrivilegioParameter, nuevoEstadoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_AsignarModuloPrivilegioInsertar(Nullable<int> idModulo, Nullable<int> idPrivilegio, Nullable<bool> estado)
        {
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(int));
    
            var idPrivilegioParameter = idPrivilegio.HasValue ?
                new ObjectParameter("IdPrivilegio", idPrivilegio) :
                new ObjectParameter("IdPrivilegio", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_AsignarModuloPrivilegioInsertar", idModuloParameter, idPrivilegioParameter, estadoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_AsignarTipoUsuarioModuloPrivilegioInsertar(Nullable<int> idTipoUsuario, Nullable<int> idAsignarModuloPrivilegio, Nullable<bool> estado)
        {
            var idTipoUsuarioParameter = idTipoUsuario.HasValue ?
                new ObjectParameter("IdTipoUsuario", idTipoUsuario) :
                new ObjectParameter("IdTipoUsuario", typeof(int));
    
            var idAsignarModuloPrivilegioParameter = idAsignarModuloPrivilegio.HasValue ?
                new ObjectParameter("IdAsignarModuloPrivilegio", idAsignarModuloPrivilegio) :
                new ObjectParameter("IdAsignarModuloPrivilegio", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_AsignarTipoUsuarioModuloPrivilegioInsertar", idTipoUsuarioParameter, idAsignarModuloPrivilegioParameter, estadoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_AsignarUsuarioTipoUsuario_insertar(Nullable<int> idUsuario, Nullable<int> idTipoUsuario, Nullable<bool> estado)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idTipoUsuarioParameter = idTipoUsuario.HasValue ?
                new ObjectParameter("IdTipoUsuario", idTipoUsuario) :
                new ObjectParameter("IdTipoUsuario", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_AsignarUsuarioTipoUsuario_insertar", idUsuarioParameter, idTipoUsuarioParameter, estadoParameter);
        }
    
        public virtual int Sp_AsignarUsuarioTipoUsuarioCambiarEstado(Nullable<int> idAsignarUsuarioTipoUsuario, Nullable<bool> nuevoEstado)
        {
            var idAsignarUsuarioTipoUsuarioParameter = idAsignarUsuarioTipoUsuario.HasValue ?
                new ObjectParameter("IdAsignarUsuarioTipoUsuario", idAsignarUsuarioTipoUsuario) :
                new ObjectParameter("IdAsignarUsuarioTipoUsuario", typeof(int));
    
            var nuevoEstadoParameter = nuevoEstado.HasValue ?
                new ObjectParameter("NuevoEstado", nuevoEstado) :
                new ObjectParameter("NuevoEstado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_AsignarUsuarioTipoUsuarioCambiarEstado", idAsignarUsuarioTipoUsuarioParameter, nuevoEstadoParameter);
        }
    
        public virtual ObjectResult<Sp_ModuloConsultar_Result> Sp_ModuloConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ModuloConsultar_Result>("Sp_ModuloConsultar");
        }
    
        public virtual int Sp_PersonaCambiarEstado(Nullable<int> idPersona, Nullable<bool> nuevoEstado)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var nuevoEstadoParameter = nuevoEstado.HasValue ?
                new ObjectParameter("NuevoEstado", nuevoEstado) :
                new ObjectParameter("NuevoEstado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PersonaCambiarEstado", idPersonaParameter, nuevoEstadoParameter);
        }
    
        public virtual ObjectResult<Sp_PrivilegioConsultar_Result> Sp_PrivilegioConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_PrivilegioConsultar_Result>("Sp_PrivilegioConsultar");
        }
    
        public virtual ObjectResult<Sp_SexoConsultar_Result> Sp_SexoConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_SexoConsultar_Result>("Sp_SexoConsultar");
        }
    
        public virtual ObjectResult<Sp_TipoIdentificacionConsultar_Result> Sp_TipoIdentificacionConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_TipoIdentificacionConsultar_Result>("Sp_TipoIdentificacionConsultar");
        }
    
        public virtual int Sp_TipoUsuarioCambiarEstado(Nullable<int> idTipoUsuario, Nullable<bool> nuevoEstado)
        {
            var idTipoUsuarioParameter = idTipoUsuario.HasValue ?
                new ObjectParameter("IdTipoUsuario", idTipoUsuario) :
                new ObjectParameter("IdTipoUsuario", typeof(int));
    
            var nuevoEstadoParameter = nuevoEstado.HasValue ?
                new ObjectParameter("NuevoEstado", nuevoEstado) :
                new ObjectParameter("NuevoEstado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_TipoUsuarioCambiarEstado", idTipoUsuarioParameter, nuevoEstadoParameter);
        }
    
        public virtual ObjectResult<Sp_TipoUsuarioConsultar_Result> Sp_TipoUsuarioConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_TipoUsuarioConsultar_Result>("Sp_TipoUsuarioConsultar");
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_TipoUsuarioInsertar(Nullable<int> identificador, string descripcion, Nullable<bool> estado)
        {
            var identificadorParameter = identificador.HasValue ?
                new ObjectParameter("Identificador", identificador) :
                new ObjectParameter("Identificador", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_TipoUsuarioInsertar", identificadorParameter, descripcionParameter, estadoParameter);
        }
    
        public virtual int Sp_TipoUsuarioModificar(Nullable<int> idTipoUsuario, Nullable<int> identificador, string descripcion)
        {
            var idTipoUsuarioParameter = idTipoUsuario.HasValue ?
                new ObjectParameter("IdTipoUsuario", idTipoUsuario) :
                new ObjectParameter("IdTipoUsuario", typeof(int));
    
            var identificadorParameter = identificador.HasValue ?
                new ObjectParameter("Identificador", identificador) :
                new ObjectParameter("Identificador", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_TipoUsuarioModificar", idTipoUsuarioParameter, identificadorParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<Sp_UsuarioBuscar_Result> Sp_UsuarioBuscar(string correo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_UsuarioBuscar_Result>("Sp_UsuarioBuscar", correoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_UsuarioInsertar(Nullable<int> idPersona, string correo, string clave, Nullable<bool> estado)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_UsuarioInsertar", idPersonaParameter, correoParameter, claveParameter, estadoParameter);
        }
    
        public virtual ObjectResult<Sp_TokenConsultar_Result2> Sp_TokenConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_TokenConsultar_Result2>("Sp_TokenConsultar");
        }
    
        public virtual ObjectResult<Sp_AsignarModuloPrivilegioConsultar_Result1> Sp_AsignarModuloPrivilegioConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AsignarModuloPrivilegioConsultar_Result1>("Sp_AsignarModuloPrivilegioConsultar");
        }
    
        public virtual ObjectResult<Sp_UsuarioValidar_Result1> Sp_UsuarioValidar(string correo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_UsuarioValidar_Result1>("Sp_UsuarioValidar", correoParameter);
        }
    
        public virtual ObjectResult<Sp_AsignarTipoUsuarioModuloPrivilegioConsultar_Result1> Sp_AsignarTipoUsuarioModuloPrivilegioConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AsignarTipoUsuarioModuloPrivilegioConsultar_Result1>("Sp_AsignarTipoUsuarioModuloPrivilegioConsultar");
        }
    
        public virtual ObjectResult<Sp_AsignarUsuarioTipoUsuarioConsultar_Result> Sp_AsignarUsuarioTipoUsuarioConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AsignarUsuarioTipoUsuarioConsultar_Result>("Sp_AsignarUsuarioTipoUsuarioConsultar");
        }
    
        public virtual ObjectResult<Sp_UsuarioInformacionGeneral_Result> Sp_UsuarioInformacionGeneral()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_UsuarioInformacionGeneral_Result>("Sp_UsuarioInformacionGeneral");
        }
    
        public virtual int Sp_PersonaEliminar(Nullable<int> idPersona)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PersonaEliminar", idPersonaParameter);
        }
    
        public virtual ObjectResult<Sp_UsuarioConsultar_Result4> Sp_UsuarioConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_UsuarioConsultar_Result4>("Sp_UsuarioConsultar");
        }
    
        public virtual int Sp_UsuarioEliminar(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UsuarioEliminar", idUsuarioParameter);
        }
    
        public virtual int Sp_UsuarioModificar(Nullable<int> idUsuario, Nullable<int> idPersona, string correo, string clave, Nullable<bool> estado)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UsuarioModificar", idUsuarioParameter, idPersonaParameter, correoParameter, claveParameter, estadoParameter);
        }
    
        public virtual int Sp_CantonEliminar(Nullable<int> idCanton)
        {
            var idCantonParameter = idCanton.HasValue ?
                new ObjectParameter("idCanton", idCanton) :
                new ObjectParameter("idCanton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_CantonEliminar", idCantonParameter);
        }
    
        public virtual int Sp_ComunidadEliminar(Nullable<int> idComunidad)
        {
            var idComunidadParameter = idComunidad.HasValue ?
                new ObjectParameter("IdComunidad", idComunidad) :
                new ObjectParameter("IdComunidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ComunidadEliminar", idComunidadParameter);
        }
    
        public virtual int Sp_ParroquiaEliminar(Nullable<int> idParroquia)
        {
            var idParroquiaParameter = idParroquia.HasValue ?
                new ObjectParameter("IdParroquia", idParroquia) :
                new ObjectParameter("IdParroquia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ParroquiaEliminar", idParroquiaParameter);
        }
    
        public virtual ObjectResult<Sp_ProvinciaConsultar_Result> Sp_ProvinciaConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ProvinciaConsultar_Result>("Sp_ProvinciaConsultar");
        }
    
        public virtual int Sp_ProvinciaEliminar(Nullable<int> idProvincia)
        {
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ProvinciaEliminar", idProvinciaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_ProvinciaInsertar(string codigoProvincia, string nombreProvincia, string descripcionProvincia, string rutaLogoProvincia, Nullable<bool> estadoProvincia)
        {
            var codigoProvinciaParameter = codigoProvincia != null ?
                new ObjectParameter("CodigoProvincia", codigoProvincia) :
                new ObjectParameter("CodigoProvincia", typeof(string));
    
            var nombreProvinciaParameter = nombreProvincia != null ?
                new ObjectParameter("NombreProvincia", nombreProvincia) :
                new ObjectParameter("NombreProvincia", typeof(string));
    
            var descripcionProvinciaParameter = descripcionProvincia != null ?
                new ObjectParameter("DescripcionProvincia", descripcionProvincia) :
                new ObjectParameter("DescripcionProvincia", typeof(string));
    
            var rutaLogoProvinciaParameter = rutaLogoProvincia != null ?
                new ObjectParameter("RutaLogoProvincia", rutaLogoProvincia) :
                new ObjectParameter("RutaLogoProvincia", typeof(string));
    
            var estadoProvinciaParameter = estadoProvincia.HasValue ?
                new ObjectParameter("EstadoProvincia", estadoProvincia) :
                new ObjectParameter("EstadoProvincia", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_ProvinciaInsertar", codigoProvinciaParameter, nombreProvinciaParameter, descripcionProvinciaParameter, rutaLogoProvinciaParameter, estadoProvinciaParameter);
        }
    
        public virtual int Sp_ProvinciaModificar(Nullable<int> idProvincia, string codigoProvincia, string nombreProvincia, string descripcionProvincia, string rutaLogoProvincia, Nullable<bool> estadoProvincia)
        {
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            var codigoProvinciaParameter = codigoProvincia != null ?
                new ObjectParameter("CodigoProvincia", codigoProvincia) :
                new ObjectParameter("CodigoProvincia", typeof(string));
    
            var nombreProvinciaParameter = nombreProvincia != null ?
                new ObjectParameter("NombreProvincia", nombreProvincia) :
                new ObjectParameter("NombreProvincia", typeof(string));
    
            var descripcionProvinciaParameter = descripcionProvincia != null ?
                new ObjectParameter("DescripcionProvincia", descripcionProvincia) :
                new ObjectParameter("DescripcionProvincia", typeof(string));
    
            var rutaLogoProvinciaParameter = rutaLogoProvincia != null ?
                new ObjectParameter("RutaLogoProvincia", rutaLogoProvincia) :
                new ObjectParameter("RutaLogoProvincia", typeof(string));
    
            var estadoProvinciaParameter = estadoProvincia.HasValue ?
                new ObjectParameter("EstadoProvincia", estadoProvincia) :
                new ObjectParameter("EstadoProvincia", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ProvinciaModificar", idProvinciaParameter, codigoProvinciaParameter, nombreProvinciaParameter, descripcionProvinciaParameter, rutaLogoProvinciaParameter, estadoProvinciaParameter);
        }
    
        public virtual ObjectResult<Sp_CantonConsultar_Result> Sp_CantonConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_CantonConsultar_Result>("Sp_CantonConsultar");
        }
    
        public virtual ObjectResult<Sp_ComunidadConsultar_Result> Sp_ComunidadConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ComunidadConsultar_Result>("Sp_ComunidadConsultar");
        }
    
        public virtual ObjectResult<Sp_ParroquiaConsultar_Result> Sp_ParroquiaConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ParroquiaConsultar_Result>("Sp_ParroquiaConsultar");
        }
    
        public virtual ObjectResult<Sp_PersonaConsultar_Result4> Sp_PersonaConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_PersonaConsultar_Result4>("Sp_PersonaConsultar");
        }
    
        public virtual ObjectResult<Sp_AsignarUsuarioTipoUsuarioConsultarNoAsignados_Result> Sp_AsignarUsuarioTipoUsuarioConsultarNoAsignados(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AsignarUsuarioTipoUsuarioConsultarNoAsignados_Result>("Sp_AsignarUsuarioTipoUsuarioConsultarNoAsignados", idUsuarioParameter);
        }
    
        public virtual ObjectResult<Sp_TipoUsuarioConsultarNoAsignadosPorUsuario_Result> Sp_TipoUsuarioConsultarNoAsignadosPorUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_TipoUsuarioConsultarNoAsignadosPorUsuario_Result>("Sp_TipoUsuarioConsultarNoAsignadosPorUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_CantonInsertar(Nullable<int> idProvincia, string codigoCanton, string nombreCanton, string descripcionCanton, string rutaLogoCanton, Nullable<bool> estadoCanton)
        {
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            var codigoCantonParameter = codigoCanton != null ?
                new ObjectParameter("CodigoCanton", codigoCanton) :
                new ObjectParameter("CodigoCanton", typeof(string));
    
            var nombreCantonParameter = nombreCanton != null ?
                new ObjectParameter("NombreCanton", nombreCanton) :
                new ObjectParameter("NombreCanton", typeof(string));
    
            var descripcionCantonParameter = descripcionCanton != null ?
                new ObjectParameter("DescripcionCanton", descripcionCanton) :
                new ObjectParameter("DescripcionCanton", typeof(string));
    
            var rutaLogoCantonParameter = rutaLogoCanton != null ?
                new ObjectParameter("RutaLogoCanton", rutaLogoCanton) :
                new ObjectParameter("RutaLogoCanton", typeof(string));
    
            var estadoCantonParameter = estadoCanton.HasValue ?
                new ObjectParameter("EstadoCanton", estadoCanton) :
                new ObjectParameter("EstadoCanton", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_CantonInsertar", idProvinciaParameter, codigoCantonParameter, nombreCantonParameter, descripcionCantonParameter, rutaLogoCantonParameter, estadoCantonParameter);
        }
    
        public virtual int Sp_CantonModificar(Nullable<int> idCanton, Nullable<int> idProvincia, string codigoCanton, string nombreCanton, string descripcionCanton, string rutaLogoCanton, Nullable<bool> estadoCanton)
        {
            var idCantonParameter = idCanton.HasValue ?
                new ObjectParameter("IdCanton", idCanton) :
                new ObjectParameter("IdCanton", typeof(int));
    
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            var codigoCantonParameter = codigoCanton != null ?
                new ObjectParameter("CodigoCanton", codigoCanton) :
                new ObjectParameter("CodigoCanton", typeof(string));
    
            var nombreCantonParameter = nombreCanton != null ?
                new ObjectParameter("NombreCanton", nombreCanton) :
                new ObjectParameter("NombreCanton", typeof(string));
    
            var descripcionCantonParameter = descripcionCanton != null ?
                new ObjectParameter("DescripcionCanton", descripcionCanton) :
                new ObjectParameter("DescripcionCanton", typeof(string));
    
            var rutaLogoCantonParameter = rutaLogoCanton != null ?
                new ObjectParameter("RutaLogoCanton", rutaLogoCanton) :
                new ObjectParameter("RutaLogoCanton", typeof(string));
    
            var estadoCantonParameter = estadoCanton.HasValue ?
                new ObjectParameter("EstadoCanton", estadoCanton) :
                new ObjectParameter("EstadoCanton", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_CantonModificar", idCantonParameter, idProvinciaParameter, codigoCantonParameter, nombreCantonParameter, descripcionCantonParameter, rutaLogoCantonParameter, estadoCantonParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_ComunidadInsertar(Nullable<int> idParroquia, string codigoComunidad, string nombreComunidad, string descripcionComunidad, string rutaLogoComunidad, Nullable<bool> estadoComunidad)
        {
            var idParroquiaParameter = idParroquia.HasValue ?
                new ObjectParameter("IdParroquia", idParroquia) :
                new ObjectParameter("IdParroquia", typeof(int));
    
            var codigoComunidadParameter = codigoComunidad != null ?
                new ObjectParameter("CodigoComunidad", codigoComunidad) :
                new ObjectParameter("CodigoComunidad", typeof(string));
    
            var nombreComunidadParameter = nombreComunidad != null ?
                new ObjectParameter("NombreComunidad", nombreComunidad) :
                new ObjectParameter("NombreComunidad", typeof(string));
    
            var descripcionComunidadParameter = descripcionComunidad != null ?
                new ObjectParameter("DescripcionComunidad", descripcionComunidad) :
                new ObjectParameter("DescripcionComunidad", typeof(string));
    
            var rutaLogoComunidadParameter = rutaLogoComunidad != null ?
                new ObjectParameter("RutaLogoComunidad", rutaLogoComunidad) :
                new ObjectParameter("RutaLogoComunidad", typeof(string));
    
            var estadoComunidadParameter = estadoComunidad.HasValue ?
                new ObjectParameter("EstadoComunidad", estadoComunidad) :
                new ObjectParameter("EstadoComunidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_ComunidadInsertar", idParroquiaParameter, codigoComunidadParameter, nombreComunidadParameter, descripcionComunidadParameter, rutaLogoComunidadParameter, estadoComunidadParameter);
        }
    
        public virtual int Sp_ComunidadModificar(Nullable<int> idComunidad, Nullable<int> idParroquia, string codigoComunidad, string nombreComunidad, string descripcionComunidad, string rutaLogoComunidad, Nullable<bool> estadoComunidad)
        {
            var idComunidadParameter = idComunidad.HasValue ?
                new ObjectParameter("IdComunidad", idComunidad) :
                new ObjectParameter("IdComunidad", typeof(int));
    
            var idParroquiaParameter = idParroquia.HasValue ?
                new ObjectParameter("IdParroquia", idParroquia) :
                new ObjectParameter("IdParroquia", typeof(int));
    
            var codigoComunidadParameter = codigoComunidad != null ?
                new ObjectParameter("CodigoComunidad", codigoComunidad) :
                new ObjectParameter("CodigoComunidad", typeof(string));
    
            var nombreComunidadParameter = nombreComunidad != null ?
                new ObjectParameter("NombreComunidad", nombreComunidad) :
                new ObjectParameter("NombreComunidad", typeof(string));
    
            var descripcionComunidadParameter = descripcionComunidad != null ?
                new ObjectParameter("DescripcionComunidad", descripcionComunidad) :
                new ObjectParameter("DescripcionComunidad", typeof(string));
    
            var rutaLogoComunidadParameter = rutaLogoComunidad != null ?
                new ObjectParameter("RutaLogoComunidad", rutaLogoComunidad) :
                new ObjectParameter("RutaLogoComunidad", typeof(string));
    
            var estadoComunidadParameter = estadoComunidad.HasValue ?
                new ObjectParameter("EstadoComunidad", estadoComunidad) :
                new ObjectParameter("EstadoComunidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ComunidadModificar", idComunidadParameter, idParroquiaParameter, codigoComunidadParameter, nombreComunidadParameter, descripcionComunidadParameter, rutaLogoComunidadParameter, estadoComunidadParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_ParroquiaInsertar(Nullable<int> idCanton, string codigoParroquia, string nombreParroquia, string descripcionParroquia, string rutaLogoParroquia, Nullable<bool> estadoParroquia)
        {
            var idCantonParameter = idCanton.HasValue ?
                new ObjectParameter("IdCanton", idCanton) :
                new ObjectParameter("IdCanton", typeof(int));
    
            var codigoParroquiaParameter = codigoParroquia != null ?
                new ObjectParameter("CodigoParroquia", codigoParroquia) :
                new ObjectParameter("CodigoParroquia", typeof(string));
    
            var nombreParroquiaParameter = nombreParroquia != null ?
                new ObjectParameter("NombreParroquia", nombreParroquia) :
                new ObjectParameter("NombreParroquia", typeof(string));
    
            var descripcionParroquiaParameter = descripcionParroquia != null ?
                new ObjectParameter("DescripcionParroquia", descripcionParroquia) :
                new ObjectParameter("DescripcionParroquia", typeof(string));
    
            var rutaLogoParroquiaParameter = rutaLogoParroquia != null ?
                new ObjectParameter("RutaLogoParroquia", rutaLogoParroquia) :
                new ObjectParameter("RutaLogoParroquia", typeof(string));
    
            var estadoParroquiaParameter = estadoParroquia.HasValue ?
                new ObjectParameter("EstadoParroquia", estadoParroquia) :
                new ObjectParameter("EstadoParroquia", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_ParroquiaInsertar", idCantonParameter, codigoParroquiaParameter, nombreParroquiaParameter, descripcionParroquiaParameter, rutaLogoParroquiaParameter, estadoParroquiaParameter);
        }
    
        public virtual int Sp_ParroquiaModificar(Nullable<int> idParroquia, Nullable<int> idCanton, string codigoParroquia, string nombreParroquia, string descripcionParroquia, string rutaLogoParroquia, Nullable<bool> estadoParroquia)
        {
            var idParroquiaParameter = idParroquia.HasValue ?
                new ObjectParameter("IdParroquia", idParroquia) :
                new ObjectParameter("IdParroquia", typeof(int));
    
            var idCantonParameter = idCanton.HasValue ?
                new ObjectParameter("IdCanton", idCanton) :
                new ObjectParameter("IdCanton", typeof(int));
    
            var codigoParroquiaParameter = codigoParroquia != null ?
                new ObjectParameter("CodigoParroquia", codigoParroquia) :
                new ObjectParameter("CodigoParroquia", typeof(string));
    
            var nombreParroquiaParameter = nombreParroquia != null ?
                new ObjectParameter("NombreParroquia", nombreParroquia) :
                new ObjectParameter("NombreParroquia", typeof(string));
    
            var descripcionParroquiaParameter = descripcionParroquia != null ?
                new ObjectParameter("DescripcionParroquia", descripcionParroquia) :
                new ObjectParameter("DescripcionParroquia", typeof(string));
    
            var rutaLogoParroquiaParameter = rutaLogoParroquia != null ?
                new ObjectParameter("RutaLogoParroquia", rutaLogoParroquia) :
                new ObjectParameter("RutaLogoParroquia", typeof(string));
    
            var estadoParroquiaParameter = estadoParroquia.HasValue ?
                new ObjectParameter("EstadoParroquia", estadoParroquia) :
                new ObjectParameter("EstadoParroquia", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ParroquiaModificar", idParroquiaParameter, idCantonParameter, codigoParroquiaParameter, nombreParroquiaParameter, descripcionParroquiaParameter, rutaLogoParroquiaParameter, estadoParroquiaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_PersonaInsertar(string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string numeroIdentificacion, Nullable<int> idTipoIdentificacion, string telefono, Nullable<int> idSexo, Nullable<int> idParroquia, string direccion, Nullable<bool> estado)
        {
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("PrimerNombre", primerNombre) :
                new ObjectParameter("PrimerNombre", typeof(string));
    
            var segundoNombreParameter = segundoNombre != null ?
                new ObjectParameter("SegundoNombre", segundoNombre) :
                new ObjectParameter("SegundoNombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var numeroIdentificacionParameter = numeroIdentificacion != null ?
                new ObjectParameter("NumeroIdentificacion", numeroIdentificacion) :
                new ObjectParameter("NumeroIdentificacion", typeof(string));
    
            var idTipoIdentificacionParameter = idTipoIdentificacion.HasValue ?
                new ObjectParameter("IdTipoIdentificacion", idTipoIdentificacion) :
                new ObjectParameter("IdTipoIdentificacion", typeof(int));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var idSexoParameter = idSexo.HasValue ?
                new ObjectParameter("IdSexo", idSexo) :
                new ObjectParameter("IdSexo", typeof(int));
    
            var idParroquiaParameter = idParroquia.HasValue ?
                new ObjectParameter("IdParroquia", idParroquia) :
                new ObjectParameter("IdParroquia", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_PersonaInsertar", primerNombreParameter, segundoNombreParameter, primerApellidoParameter, segundoApellidoParameter, numeroIdentificacionParameter, idTipoIdentificacionParameter, telefonoParameter, idSexoParameter, idParroquiaParameter, direccionParameter, estadoParameter);
        }
    
        public virtual int Sp_PersonaModificar(Nullable<int> idPersona, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string numeroIdentificacion, Nullable<int> idTipoIdentificacion, string telefono, Nullable<int> idSexo, Nullable<int> idParroquia, string direccion, Nullable<bool> estado)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("PrimerNombre", primerNombre) :
                new ObjectParameter("PrimerNombre", typeof(string));
    
            var segundoNombreParameter = segundoNombre != null ?
                new ObjectParameter("SegundoNombre", segundoNombre) :
                new ObjectParameter("SegundoNombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var numeroIdentificacionParameter = numeroIdentificacion != null ?
                new ObjectParameter("NumeroIdentificacion", numeroIdentificacion) :
                new ObjectParameter("NumeroIdentificacion", typeof(string));
    
            var idTipoIdentificacionParameter = idTipoIdentificacion.HasValue ?
                new ObjectParameter("IdTipoIdentificacion", idTipoIdentificacion) :
                new ObjectParameter("IdTipoIdentificacion", typeof(int));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var idSexoParameter = idSexo.HasValue ?
                new ObjectParameter("IdSexo", idSexo) :
                new ObjectParameter("IdSexo", typeof(int));
    
            var idParroquiaParameter = idParroquia.HasValue ?
                new ObjectParameter("IdParroquia", idParroquia) :
                new ObjectParameter("IdParroquia", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PersonaModificar", idPersonaParameter, primerNombreParameter, segundoNombreParameter, primerApellidoParameter, segundoApellidoParameter, numeroIdentificacionParameter, idTipoIdentificacionParameter, telefonoParameter, idSexoParameter, idParroquiaParameter, direccionParameter, estadoParameter);
        }
    
        public virtual ObjectResult<Sp_AlcaldeConsultar_Result> Sp_AlcaldeConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AlcaldeConsultar_Result>("Sp_AlcaldeConsultar");
        }
    
        public virtual ObjectResult<Sp_LiderComunitarioConsultar_Result> Sp_LiderComunitarioConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_LiderComunitarioConsultar_Result>("Sp_LiderComunitarioConsultar");
        }
    
        public virtual ObjectResult<Sp_PrefectoConsultar_Result> Sp_PrefectoConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_PrefectoConsultar_Result>("Sp_PrefectoConsultar");
        }
    
        public virtual ObjectResult<Sp_PresidenteJuntaParroquialConsultar_Result1> Sp_PresidenteJuntaParroquialConsultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_PresidenteJuntaParroquialConsultar_Result1>("Sp_PresidenteJuntaParroquialConsultar");
        }
    
        public virtual int Sp_AlcaldeEliminar(Nullable<int> idAlcalde)
        {
            var idAlcaldeParameter = idAlcalde.HasValue ?
                new ObjectParameter("IdAlcalde", idAlcalde) :
                new ObjectParameter("IdAlcalde", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_AlcaldeEliminar", idAlcaldeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_AlcaldeInsertar(Nullable<int> idCanton, string representante, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaSalida, Nullable<bool> estadoAlcalde)
        {
            var idCantonParameter = idCanton.HasValue ?
                new ObjectParameter("IdCanton", idCanton) :
                new ObjectParameter("IdCanton", typeof(int));
    
            var representanteParameter = representante != null ?
                new ObjectParameter("Representante", representante) :
                new ObjectParameter("Representante", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var estadoAlcaldeParameter = estadoAlcalde.HasValue ?
                new ObjectParameter("EstadoAlcalde", estadoAlcalde) :
                new ObjectParameter("EstadoAlcalde", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_AlcaldeInsertar", idCantonParameter, representanteParameter, fechaIngresoParameter, fechaSalidaParameter, estadoAlcaldeParameter);
        }
    
        public virtual int Sp_AlcaldeModificar(Nullable<int> idAlcalde, Nullable<int> idCanton, string representante, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaSalida, Nullable<bool> estadoAlcalde)
        {
            var idAlcaldeParameter = idAlcalde.HasValue ?
                new ObjectParameter("IdAlcalde", idAlcalde) :
                new ObjectParameter("IdAlcalde", typeof(int));
    
            var idCantonParameter = idCanton.HasValue ?
                new ObjectParameter("IdCanton", idCanton) :
                new ObjectParameter("IdCanton", typeof(int));
    
            var representanteParameter = representante != null ?
                new ObjectParameter("Representante", representante) :
                new ObjectParameter("Representante", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var estadoAlcaldeParameter = estadoAlcalde.HasValue ?
                new ObjectParameter("EstadoAlcalde", estadoAlcalde) :
                new ObjectParameter("EstadoAlcalde", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_AlcaldeModificar", idAlcaldeParameter, idCantonParameter, representanteParameter, fechaIngresoParameter, fechaSalidaParameter, estadoAlcaldeParameter);
        }
    
        public virtual int Sp_LiderComunitarioEliminar(Nullable<int> idLiderComunitario)
        {
            var idLiderComunitarioParameter = idLiderComunitario.HasValue ?
                new ObjectParameter("IdLiderComunitario", idLiderComunitario) :
                new ObjectParameter("IdLiderComunitario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_LiderComunitarioEliminar", idLiderComunitarioParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_LiderComunitarioInsertar(Nullable<int> idComunidad, string representante, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaSalida, Nullable<bool> estadoLiderComunitario)
        {
            var idComunidadParameter = idComunidad.HasValue ?
                new ObjectParameter("IdComunidad", idComunidad) :
                new ObjectParameter("IdComunidad", typeof(int));
    
            var representanteParameter = representante != null ?
                new ObjectParameter("Representante", representante) :
                new ObjectParameter("Representante", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var estadoLiderComunitarioParameter = estadoLiderComunitario.HasValue ?
                new ObjectParameter("EstadoLiderComunitario", estadoLiderComunitario) :
                new ObjectParameter("EstadoLiderComunitario", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_LiderComunitarioInsertar", idComunidadParameter, representanteParameter, fechaIngresoParameter, fechaSalidaParameter, estadoLiderComunitarioParameter);
        }
    
        public virtual int Sp_LiderComunitarioModificar(Nullable<int> idLiderComunitario, Nullable<int> idComunidad, string representante, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaSalida, Nullable<bool> estadoPresidenteJuntaParroquial)
        {
            var idLiderComunitarioParameter = idLiderComunitario.HasValue ?
                new ObjectParameter("IdLiderComunitario", idLiderComunitario) :
                new ObjectParameter("IdLiderComunitario", typeof(int));
    
            var idComunidadParameter = idComunidad.HasValue ?
                new ObjectParameter("IdComunidad", idComunidad) :
                new ObjectParameter("IdComunidad", typeof(int));
    
            var representanteParameter = representante != null ?
                new ObjectParameter("Representante", representante) :
                new ObjectParameter("Representante", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var estadoPresidenteJuntaParroquialParameter = estadoPresidenteJuntaParroquial.HasValue ?
                new ObjectParameter("EstadoPresidenteJuntaParroquial", estadoPresidenteJuntaParroquial) :
                new ObjectParameter("EstadoPresidenteJuntaParroquial", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_LiderComunitarioModificar", idLiderComunitarioParameter, idComunidadParameter, representanteParameter, fechaIngresoParameter, fechaSalidaParameter, estadoPresidenteJuntaParroquialParameter);
        }
    
        public virtual int Sp_PrefectoEliminar(Nullable<int> idPrefecto)
        {
            var idPrefectoParameter = idPrefecto.HasValue ?
                new ObjectParameter("IdPrefecto", idPrefecto) :
                new ObjectParameter("IdPrefecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PrefectoEliminar", idPrefectoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_PrefectoInsertar(Nullable<int> idProvincia, string representante, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaSalida, Nullable<bool> estadoPrefecto)
        {
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            var representanteParameter = representante != null ?
                new ObjectParameter("Representante", representante) :
                new ObjectParameter("Representante", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var estadoPrefectoParameter = estadoPrefecto.HasValue ?
                new ObjectParameter("EstadoPrefecto", estadoPrefecto) :
                new ObjectParameter("EstadoPrefecto", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_PrefectoInsertar", idProvinciaParameter, representanteParameter, fechaIngresoParameter, fechaSalidaParameter, estadoPrefectoParameter);
        }
    
        public virtual int Sp_PrefectoModificar(Nullable<int> idPrefecto, Nullable<int> idProvincia, string representante, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaSalida, Nullable<bool> estadoPrefecto)
        {
            var idPrefectoParameter = idPrefecto.HasValue ?
                new ObjectParameter("IdPrefecto", idPrefecto) :
                new ObjectParameter("IdPrefecto", typeof(int));
    
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            var representanteParameter = representante != null ?
                new ObjectParameter("Representante", representante) :
                new ObjectParameter("Representante", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var estadoPrefectoParameter = estadoPrefecto.HasValue ?
                new ObjectParameter("EstadoPrefecto", estadoPrefecto) :
                new ObjectParameter("EstadoPrefecto", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PrefectoModificar", idPrefectoParameter, idProvinciaParameter, representanteParameter, fechaIngresoParameter, fechaSalidaParameter, estadoPrefectoParameter);
        }
    
        public virtual int Sp_PresidenteJuntaParroquialEliminar(Nullable<int> idPresidenteJuntaParroquial)
        {
            var idPresidenteJuntaParroquialParameter = idPresidenteJuntaParroquial.HasValue ?
                new ObjectParameter("IdPresidenteJuntaParroquial", idPresidenteJuntaParroquial) :
                new ObjectParameter("IdPresidenteJuntaParroquial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PresidenteJuntaParroquialEliminar", idPresidenteJuntaParroquialParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_PresidenteJuntaParroquialInsertar(Nullable<int> idParroquia, string representante, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaSalida, Nullable<bool> estadoPresidenteJuntaParroquial)
        {
            var idParroquiaParameter = idParroquia.HasValue ?
                new ObjectParameter("IdParroquia", idParroquia) :
                new ObjectParameter("IdParroquia", typeof(int));
    
            var representanteParameter = representante != null ?
                new ObjectParameter("Representante", representante) :
                new ObjectParameter("Representante", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var estadoPresidenteJuntaParroquialParameter = estadoPresidenteJuntaParroquial.HasValue ?
                new ObjectParameter("EstadoPresidenteJuntaParroquial", estadoPresidenteJuntaParroquial) :
                new ObjectParameter("EstadoPresidenteJuntaParroquial", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_PresidenteJuntaParroquialInsertar", idParroquiaParameter, representanteParameter, fechaIngresoParameter, fechaSalidaParameter, estadoPresidenteJuntaParroquialParameter);
        }
    
        public virtual int Sp_PresidenteJuntaParroquialModificar(Nullable<int> idPresidenteJuntaParroquial, Nullable<int> idParroquia, string representante, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaSalida, Nullable<bool> estadoPresidenteJuntaParroquial)
        {
            var idPresidenteJuntaParroquialParameter = idPresidenteJuntaParroquial.HasValue ?
                new ObjectParameter("IdPresidenteJuntaParroquial", idPresidenteJuntaParroquial) :
                new ObjectParameter("IdPresidenteJuntaParroquial", typeof(int));
    
            var idParroquiaParameter = idParroquia.HasValue ?
                new ObjectParameter("IdParroquia", idParroquia) :
                new ObjectParameter("IdParroquia", typeof(int));
    
            var representanteParameter = representante != null ?
                new ObjectParameter("Representante", representante) :
                new ObjectParameter("Representante", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var estadoPresidenteJuntaParroquialParameter = estadoPresidenteJuntaParroquial.HasValue ?
                new ObjectParameter("EstadoPresidenteJuntaParroquial", estadoPresidenteJuntaParroquial) :
                new ObjectParameter("EstadoPresidenteJuntaParroquial", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PresidenteJuntaParroquialModificar", idPresidenteJuntaParroquialParameter, idParroquiaParameter, representanteParameter, fechaIngresoParameter, fechaSalidaParameter, estadoPresidenteJuntaParroquialParameter);
        }
    }
}
