//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Conexion
{
    using System;
    
    public partial class Sp_AsignarModuloPrivilegioConsultar_Result1
    {
        public int IdAsignarModuloPrivilegio { get; set; }
        public int IdModulo { get; set; }
        public int IdPrivilegio { get; set; }
        public bool Estado { get; set; }
    }
}
