//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Conexion
{
    using System;
    
    public partial class Sp_AsignarTipoUsuarioModuloPrivilegioConsultar_Result1
    {
        public int TIPOUSUARIO_IdTipoUsuario { get; set; }
        public int TIPOUSUARIO_Identificador { get; set; }
        public string TIPOUSUARIO_Descripcion { get; set; }
        public bool TIPOUSUARIO_Estado { get; set; }
        public int ASIGNARTIPOUSUARIOMODULOPRIVILEGIO_IdAsignarTipoUsuarioModuloPrivilegio { get; set; }
        public int ASIGNARTIPOUSUARIOMODULOPRIVILEGIO_IdTipoUsuario { get; set; }
        public int ASIGNARTIPOUSUARIOMODULOPRIVILEGIO_IdAsignarModuloPrivilegio { get; set; }
        public bool ASIGNARTIPOUSUARIOMODULOPRIVILEGIO_Estado { get; set; }
        public int ASIGNARMODULOPRIVILEGIO_IdAsignarModuloPrivilegio { get; set; }
        public int ASIGNARMODULOPRIVILEGIO_IdModulo { get; set; }
        public int ASIGNARMODULOPRIVILEGIO_IdPrivilegio { get; set; }
        public bool ASIGNARMODULOPRIVILEGIO_Estado { get; set; }
        public int MODULO_IdModulo { get; set; }
        public int MODULO_Identificador { get; set; }
        public string MODULO_Descripcion { get; set; }
        public bool MODULO_Estado { get; set; }
        public int PRIVILEGIO_IdPrivilegio { get; set; }
        public int PRIVILEGIO_Identificador { get; set; }
        public string PRIVILEGIO_Descripcion { get; set; }
        public bool PRIVILEGIO_Estado { get; set; }
    }
}
